In [90]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

np.set_printoptions(precision=4, suppress=True)

In [91]:
df = pd.read_csv("world-happiness-report-2021.csv")
df = df[['Country name', 'Ladder score',
         'Logged GDP per capita', 'Social support',
         'Healthy life expectancy', 'Freedom to make life choices',
         'Generosity', 'Perceptions of corruption']]

df = df.rename(columns={
    'Country name': 'Country',
    'Ladder score': 'Happiness',
    'Logged GDP per capita': 'GDP',
    'Social support': 'Social',
    'Healthy life expectancy': 'Life',
    'Freedom to make life choices': 'Freedom',
    'Perceptions of corruption': 'Corruption'
})

df = df.set_index('Country')

df

,Happiness,GDP,Social,Life,Freedom,Generosity,Corruption
Country,,,,,,,
Finland,7.842,10.775,0.954,72.000,0.949,-0.098,0.186
Denmark,7.620,10.933,0.954,72.700,0.946,0.030,0.179
Switzerland,7.571,11.117,0.942,74.400,0.919,0.025,0.292
Iceland,7.554,10.878,0.983,73.000,0.955,0.160,0.673
Netherlands,7.464,10.932,0.942,72.400,0.913,0.175,0.338
...,...,...,...,...,...,...,...
Lesotho,3.512,7.926,0.787,48.700,0.715,-0.131,0.915
Botswana,3.467,9.782,0.784,59.269,0.824,-0.246,0.801
Rwanda,3.415,7.676,0.552,61.400,0.897,0.061,0.167
Zimbabwe,3.145,7.943,0.750,56.201,0.677,-0.047,0.821
Afghanistan,2.523,7.695,0.463,52.493,0.382,-0.102,0.924

In [92]:
df = df - df.mean()
df

,Happiness,GDP,Social,Life,Freedom,Generosity,Corruption
Country,,,,,,,
Finland,2.309161,1.342792,0.139255,7.007201,0.157403,-0.082866,-0.54145
Denmark,2.087161,1.500792,0.139255,7.707201,0.154403,0.045134,-0.54845
Switzerland,2.038161,1.684792,0.127255,9.407201,0.127403,0.040134,-0.43545
Iceland,2.021161,1.445792,0.168255,8.007201,0.163403,0.175134,-0.05445
Netherlands,1.931161,1.499792,0.127255,7.407201,0.121403,0.190134,-0.38945
...,...,...,...,...,...,...,...
Lesotho,-2.020839,-1.506208,-0.027745,-16.292799,-0.076597,-0.115866,0.18755
Botswana,-2.065839,0.349792,-0.030745,-5.723799,0.032403,-0.230866,0.07355
Rwanda,-2.117839,-1.756208,-0.262745,-3.592799,0.105403,0.076134,-0.56045
Zimbabwe,-2.387839,-1.489208,-0.064745,-8.791799,-0.114597,-0.031866,0.09355
Afghanistan,-3.009839,-1.737208,-0.351745,-12.499799,-0.409597,-0.086866,0.19655

In [93]:
df.loc["India"]
df.loc["Pakistan"]

Happiness    -1.713839
GDP          -0.677208
Social       -0.211745
Life         -4.359799
Freedom       0.101403
Generosity    0.104134
Corruption    0.046550
Name: India, dtype: float64

Happiness    -0.598839
GDP          -0.974208
Social       -0.163745
Life         -6.283799
Freedom      -0.065597
Generosity    0.113134
Corruption    0.059550
Name: Pakistan, dtype: float64

In [94]:
df.sort_values(by='Freedom', ascending=False).loc["South Korea"]

Happiness     0.312161
GDP           1.218792
Social       -0.015745
Life          8.907201
Freedom      -0.119597
Generosity   -0.067866
Corruption   -0.000450
Name: South Korea, dtype: float64

In [95]:
X = df.values.T
X.shape

(7, 149)

In [96]:
n = X.shape[1]
C = X @ X.T / n
C.shape

(7, 7)

In [97]:
import numpy as np

In [98]:
eigenvalues, eigenvectors = np.linalg.eig(C)
eigenvectors = eigenvectors.T

eigenvalues
eigenvectors

array([47.1136,  0.5655,  0.2401,  0.0294,  0.0178,  0.0074,  0.0038])

array([[-0.1215, -0.1461, -0.0122, -0.9816, -0.0077,  0.0035,  0.0096],
       [ 0.817 ,  0.5398,  0.0547, -0.1829,  0.0488,  0.0169, -0.0457],
       [-0.5503,  0.825 ,  0.0174, -0.0542, -0.0594, -0.085 ,  0.051 ],
       [ 0.096 , -0.0514,  0.0855,  0.0025, -0.1617, -0.4809,  0.8505],
       [-0.0288,  0.0429,  0.0896,  0.0033,  0.0891,  0.8564,  0.498 ],
       [ 0.0651,  0.0017, -0.2433,  0.0021, -0.9508,  0.1667, -0.0693],
       [-0.0275, -0.0466,  0.9602, -0.0011, -0.2366,  0.0058, -0.1379]])